CREATE TABLE `user` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`age` INT(11) NULL DEFAULT NULL,
	`name` VARCHAR(50) NULL DEFAULT NULL,
	`address` VARCHAR(50) NULL DEFAULT NULL,
	`sex` TINYINT(4) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
ENGINE=InnoDB
AUTO_INCREMENT=0
;